"""Set refresh_token length

Revision ID: 0ecc8f116f3e
Revises: 773e1e78eec6
Create Date: 2026-08-25 14:29:17.644056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecc8f116f3e'
down_revision: Union[str, Sequence[str], None] = '773e1e78eec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token', type_=sa.String(255))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token', type_=sa.String())
    # ### end Alembic commands ###
