"""Update users table

Revision ID: 773e1e78eec6
Revises: 2f3c676d380f
Create Date: 2026-08-25 14:12:41.706484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773e1e78eec6'
down_revision: Union[str, Sequence[str], None] = '2f3c676d380f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expires_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'token_expires_at')
    # ### end Alembic commands ###
