"""Add triggered_by_user_id to agent_runs

Revision ID: dace00765659
Revises: ebdb98b7fd48
Create Date: 2026-09-05 23:55:47.011203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dace00765659'
down_revision: Union[str, Sequence[str], None] = 'ebdb98b7fd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('triggered_by_user_id', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE agent_runs SET triggered_by_user_id = (SELECT id FROM users ORDER BY id LIMIT 1)"
    )
    op.alter_column('agent_runs', 'triggered_by_user_id', nullable=False)
    op.create_foreign_key(None, 'agent_runs', 'users', ['triggered_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_column('agent_runs', 'triggered_by_user_id')
    # ### end Alembic commands ###
