"""Add webhook_id to repositories

Revision ID: e31dfe69022c
Revises: dace00765659
Create Date: 2026-09-06 19:06:16.157532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31dfe69022c'
down_revision: Union[str, Sequence[str], None] = 'dace00765659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('webhook_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'webhook_id')
    # ### end Alembic commands ###
