"""Add user repositories join table and remove userid from repositories

Revision ID: ebdb98b7fd48
Revises: 0ecc8f116f3e
Create Date: 2026-08-29 10:27:43.316128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdb98b7fd48'
down_revision: Union[str, Sequence[str], None] = '0ecc8f116f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo_id', name='uq_user_repo')
    )
    op.drop_constraint(op.f('repositories_user_id_fkey'), 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('repositories_user_id_fkey'), 'repositories', 'users', ['user_id'], ['id'])
    op.drop_table('user_repositories')
    # ### end Alembic commands ###
